# Generated by Django 5.1 on 2024-08-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='content_paragraph_1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_paragraph_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_paragraph_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
